User.create(username: "BSisko", password: "test")
User.create(username: "Nerys", password: "test")
User.create(username: "UnknownSample", password: "test")
User.create(username: "Number1Doc", password: "test")
User.create(username: "JustASimpleTailor", password: "test")
User.create(username: "TheOnlyNCO", password: "test")
User.create(username: "GoToQuarksDontWalkRun", password: "test")
User.create(username: "WormFan2463", password: "test")
User.create(username: "IAmNotAMerryMan", password: "test")
User.create(username: "JLPicard", password: "test")



Book.create(title: "Baseball: An Illustraated History", author: "Geoffrey C. Ward", published: "1996", user_id: 1)
Book.create(title: "Baseball Scorekeeping: A Practical Guide to the Rules", author: "Andres Wirkmaa", published: "2010", user_id: 1)
Book.create(title: "Malcolm X Speaks: Selected Speeches and Statements", author: "George Breitman", published: "1990", user_id: 1)
Book.create(title: "Comparative Religion", author: "Kedar Nath Tiwari", published: "2014", user_id: 2)
Book.create(title: "Insurgency and Counter-Insurgency in Iraq", author: "Ahmed S. Hashim", published: "2011", user_id: 2)
Book.create(title: "Counterinsurgency: FM 3-24 (2006)", author: "U.S. Army, David H Petraeues, James F. Amos", published: "2007", user_id: 2)
Book.create(title: "Who Am I?- And If So, How Many?: A Philosophical Journey", author: "Author Name", published: "2011", user_id: 3)
Book.create(title: "How to Win Friends and Influence People", author: "Dale Carnegie", published: "1936", user_id: 3)
Book.create(title: "Adventures of Sherlock Holmes", author: "Sir Arthur Conan Doyle", published: "1900", user_id: 3)
Book.create(title: "The Genuine Works of Hippocrates - Volume 1", author: "Hippocrates, Francis Adams", published: "1886", user_id: 4)
Book.create(title: "Pliny's Natural History. In Thirty-seven Books - Volumes 1-3", author: "Pliny (the Elder)", published: "1848", user_id: 4)
Book.create(title: "The Life and Times of Paddington Bear", author: "Russel Ash, Michael Bond", published: "1988", user_id: 4)
Book.create(title: "Espionage: The Greatest Spy Operations of the Twentieth Century", author: "Ernest Volkman", published: "1995", user_id: 5)
Book.create(title: "The Origins of Totalitarianism", author: "Hannah Arendt", published: "1973", user_id: 5)
Book.create(title: "The Complete Book od Tailoring", author: "Adele P. Margolis", published: "2019", user_id: 5)
Book.create(title: "Ulysses", author: "James Joyce", published: "1922", user_id: 6)
Book.create(title: "Performance Kayaking", author: "Stephen B. U'Ren", published: "1990", user_id: 6)
Book.create(title: "Engineering Drawing", author: "Basant Agrawal", published: "2008", user_id: 6)
Book.create(title: "Bartending For Dummies", author: "Ray Foley", published: "2006", user_id: 7)
Book.create(title: "Restaurant Business: How to Start and be Successful", author: "Anthony Ekanem", published: "2016", user_id: 7)
Book.create(title: "Symbiosis", author: "Alvin Silverstein, ‎Virginia B. Silverstein, ‎Laura Silverstein Nunn", published: "2007", user_id: 8)
Book.create(title: "The Universe in a Nutshell", author: "Stephen Hawking", published: "2001", user_id: 8)
Book.create(title: "A Smart Girl's Guide to Parties", author: "Apryl Lundsten", published: "2010", user_id: 8)
Book.create(title: "Klingon for the Galactic Traveler", author: "Marc Okrand", published: "2012", user_id: 9)
Book.create(title: "The Art of War", author: "Sun Tzu", published: "-500", user_id: 9)
Book.create(title: "Opera", author: "Crystal Kirgiss", published: "2004", user_id: 9)
Book.create(title: "A Little Tea Book: All the Essentials from Leaf to Cup", author: "Sebastian Beckwith, Caroline Paul", published: "2018", user_id: 10)
Book.create(title: "Archaeology, Cultural Property, and the Military", author: "Laurie Rush", published: "2010", user_id: 10)


Message.create(sender_id: 1, recipient_id: 2, content: "Some text", read: false)
Message.create(sender_id: 1, recipient_id: 2, content: "Some different text", read: false)
Message.create(sender_id: 2, recipient_id: 1, content: "Some text in response", read: false)