User.create(username: "Test", password: "Test")
Book.create(title: "Title", author: "Author Name", published: "1969", user_id: 1)
Book.create(title: "Title", author: "Author Name", published: "1969", user_id: 1)
Book.create(title: "Title that is medium", author: "Author Name", published: "1969", user_id: 1)
Book.create(title: "Title", author: "Author Name", published: "1969", user_id: 1)
Book.create(title: "Title", author: "Author Name", published: "1969", user_id: 1)
Book.create(title: "Title that is Kind of Long", author: "Author Name", published: "1969", user_id: 1)
Book.create(title: "Title that is medium", author: "Author Name", published: "1969", user_id: 1)
Book.create(title: "Title of book", author: "Author Name", published: "1969", user_id: 1)
Book.create(title: "Title", author: "Author Name", published: "1969", user_id: 1)
Book.create(title: "Title", author: "Author Name", published: "1969", user_id: 1)
Book.create(title: "Title", author: "Author Name", published: "1969", user_id: 1)
Book.create(title: "Title that is Kind of Long", author: "Author Name", published: "1969", user_id: 1)
Book.create(title: "Title", author: "Author Name", published: "1969", user_id: 1)
Book.create(title: "Title that is Kind of Long", author: "Author Name", published: "1969", user_id: 1)
Book.create(title: "A Really Long Title that Goes On for a While", author: "Author Name", published: "1969", user_id: 1)
